# Generated by Django 5.0.14 on 2026-02-01 14:48

import apps.orders.models.order_file
import django.core.validators
import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="order number",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="order title")),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the order requirements",
                        max_length=5000,
                        verbose_name="description",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="e.g., Computer Science, Business, Psychology",
                        max_length=200,
                        verbose_name="subject area",
                    ),
                ),
                (
                    "academic_level",
                    models.CharField(
                        choices=[
                            ("high_school", "High School"),
                            ("undergraduate", "Undergraduate"),
                            ("bachelors", "Bachelor's"),
                            ("masters", "Master's"),
                            ("phd", "PhD"),
                            ("professional", "Professional"),
                        ],
                        default="undergraduate",
                        max_length=20,
                        verbose_name="academic level",
                    ),
                ),
                (
                    "pages",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="number of pages",
                    ),
                ),
                (
                    "words",
                    models.PositiveIntegerField(
                        default=275,
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(50000),
                        ],
                        verbose_name="number of words",
                    ),
                ),
                (
                    "sources",
                    models.PositiveIntegerField(
                        default=3,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="number of sources",
                    ),
                ),
                (
                    "formatting_style",
                    models.CharField(
                        default="APA",
                        help_text="e.g., APA, MLA, Chicago, Harvard",
                        max_length=50,
                        verbose_name="formatting style",
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("standard", "Standard (14 days)"),
                            ("urgent", "Urgent (7 days)"),
                            ("very_urgent", "Very Urgent (3 days)"),
                            ("emergency", "Emergency (24 hours)"),
                        ],
                        default="standard",
                        max_length=20,
                        verbose_name="urgency level",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        help_text="Final deadline for order completion",
                        verbose_name="deadline",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total price in platform currency",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="price",
                    ),
                ),
                (
                    "writer_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Amount to be paid to writer",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="writer payment",
                    ),
                ),
                (
                    "platform_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Platform commission",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="platform fee",
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("draft", "Draft"),
                            ("paid", "Paid"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("delivered", "Delivered"),
                            ("revision_requested", "Revision Requested"),
                            ("in_revision", "In Revision"),
                            ("completed", "Completed"),
                            ("disputed", "Disputed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=50,
                        protected=True,
                        verbose_name="order state",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="paid at"),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="assigned at"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="started at"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="delivered at"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="cancelled at"
                    ),
                ),
                (
                    "revision_count",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(10)],
                        verbose_name="revision count",
                    ),
                ),
                (
                    "max_revisions",
                    models.PositiveIntegerField(
                        default=3, verbose_name="maximum revisions"
                    ),
                ),
                (
                    "dispute_reason",
                    models.TextField(blank=True, verbose_name="dispute reason"),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="refund amount",
                    ),
                ),
                (
                    "refunded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="refunded at"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="admin notes"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigned by",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="client",
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="writer_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="writer",
                    ),
                ),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "formatting_correct",
                    models.BooleanField(
                        default=False,
                        help_text="Document follows specified formatting style",
                        verbose_name="formatting correct",
                    ),
                ),
                (
                    "structure_proper",
                    models.BooleanField(
                        default=False,
                        help_text="Document has proper structure (introduction, body, conclusion)",
                        verbose_name="structure proper",
                    ),
                ),
                (
                    "page_count_met",
                    models.BooleanField(
                        default=False,
                        help_text="Document meets required page count",
                        verbose_name="page count met",
                    ),
                ),
                (
                    "word_count_met",
                    models.BooleanField(
                        default=False,
                        help_text="Document meets required word count",
                        verbose_name="word count met",
                    ),
                ),
                (
                    "instructions_followed",
                    models.BooleanField(
                        default=False,
                        help_text="All client instructions have been followed",
                        verbose_name="instructions followed",
                    ),
                ),
                (
                    "topic_adherence",
                    models.BooleanField(
                        default=False,
                        help_text="Document stays on topic and addresses all requirements",
                        verbose_name="topic adherence",
                    ),
                ),
                (
                    "argument_coherence",
                    models.BooleanField(
                        default=False,
                        help_text="Arguments are coherent and logically presented",
                        verbose_name="argument coherence",
                    ),
                ),
                (
                    "sources_cited",
                    models.BooleanField(
                        default=False,
                        help_text="Required number of sources are cited",
                        verbose_name="sources cited",
                    ),
                ),
                (
                    "citation_proper",
                    models.BooleanField(
                        default=False,
                        help_text="Citations follow specified style correctly",
                        verbose_name="citation proper",
                    ),
                ),
                (
                    "plagiarism_free",
                    models.BooleanField(
                        default=False,
                        help_text="Document has been checked for plagiarism",
                        verbose_name="plagiarism free",
                    ),
                ),
                (
                    "grammar_correct",
                    models.BooleanField(
                        default=False,
                        help_text="Grammar and spelling are correct",
                        verbose_name="grammar correct",
                    ),
                ),
                (
                    "language_appropriate",
                    models.BooleanField(
                        default=False,
                        help_text="Language is appropriate for academic level",
                        verbose_name="language appropriate",
                    ),
                ),
                (
                    "additional_files",
                    models.BooleanField(
                        default=False,
                        help_text="All required additional files are included",
                        verbose_name="additional files included",
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes from quality review",
                        verbose_name="review notes",
                    ),
                ),
                (
                    "passed_quality_check",
                    models.BooleanField(
                        default=False, verbose_name="passed quality check"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_checklists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reviewed by",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_checklist",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
            ],
            options={
                "verbose_name": "delivery checklist",
                "verbose_name_plural": "delivery checklists",
            },
        ),
        migrations.CreateModel(
            name="OrderFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("instructions", "Instructions"),
                            ("reference", "Reference Material"),
                            ("submission", "Submission"),
                            ("revision", "Revision"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="file type",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload relevant order files (max 20MB)",
                        upload_to=apps.orders.models.order_file.order_file_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "ppt",
                                    "pptx",
                                    "xls",
                                    "xlsx",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "zip",
                                    "rar",
                                ]
                            )
                        ],
                        verbose_name="file",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Brief description of the file contents",
                        max_length=500,
                        verbose_name="description",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processed", "Processed"),
                            ("rejected", "Rejected"),
                        ],
                        default="uploaded",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash for integrity verification",
                        max_length=128,
                        verbose_name="file hash",
                    ),
                ),
                (
                    "scanned_for_virus",
                    models.BooleanField(
                        default=False, verbose_name="scanned for virus"
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="original filename"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(verbose_name="file size in bytes"),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="MIME type"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="version"),
                ),
                (
                    "is_final",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as final submission version",
                        verbose_name="is final version",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uploaded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "order file",
                "verbose_name_plural": "order files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_number"], name="orders_orde_order_n_f3ada5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["state"], name="orders_orde_state_d5ccd0_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["client", "state"], name="orders_orde_client__7e7773_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["writer", "state"], name="orders_orde_writer__716a1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["deadline"], name="orders_orde_deadlin_d3e42d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["academic_level"], name="orders_orde_academi_f776da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["subject"], name="orders_orde_subject_ce756c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderfile",
            index=models.Index(
                fields=["order", "file_type"], name="orders_orde_order_i_472177_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderfile",
            index=models.Index(
                fields=["uploaded_by"], name="orders_orde_uploade_02772a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderfile",
            index=models.Index(fields=["status"], name="orders_orde_status_42df78_idx"),
        ),
        migrations.AddIndex(
            model_name="orderfile",
            index=models.Index(
                fields=["is_final"], name="orders_orde_is_fina_a1d798_idx"
            ),
        ),
    ]
