# Generated by Django 4.2.7 on 2026-02-13 23:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Order for display')),
                ('inquiry_type', models.CharField(choices=[('general', 'General Question'), ('license', 'Licensing Request'), ('print', 'Print Purchase'), ('commission', 'Commission Work'), ('collaboration', 'Collaboration'), ('interview', 'Interview Request'), ('workshop', 'Workshop/Teaching'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('usage_type', models.CharField(blank=True, help_text='How will the media be used? (for licensing)', max_length=200)),
                ('deadline', models.DateField(blank=True, help_text='Project deadline', null=True)),
                ('budget_range', models.CharField(blank=True, help_text='Budget range for the project', max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='new', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True, help_text='Internal notes about response')),
                ('accepted_terms', models.BooleanField(default=False)),
                ('accepted_privacy', models.BooleanField(default=False)),
                ('media_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='media.mediaitem')),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='inquiries_i_status_152cc6_idx'), models.Index(fields=['inquiry_type', 'status'], name='inquiries_i_inquiry_a4e2f7_idx')],
            },
        ),
    ]
