# Generated by Django 5.0.14 on 2026-02-01 13:22

import apps.accounts.models.writer_document
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Required. Must be a valid email address.",
                        max_length=254,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("writer", "Writer"),
                            ("admin", "Admin"),
                            ("moderator", "Moderator"),
                        ],
                        default="client",
                        max_length=20,
                        verbose_name="user type",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="International format (e.g., +1234567890)",
                        max_length=20,
                        null=True,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "terms_accepted",
                    models.BooleanField(
                        default=False,
                        help_text="User has accepted the terms and conditions.",
                        verbose_name="terms accepted",
                    ),
                ),
                (
                    "privacy_policy_accepted",
                    models.BooleanField(
                        default=False,
                        help_text="User has accepted the privacy policy.",
                        verbose_name="privacy policy accepted",
                    ),
                ),
                (
                    "marketing_emails",
                    models.BooleanField(
                        default=False,
                        help_text="User has consented to marketing emails.",
                        verbose_name="marketing emails",
                    ),
                ),
                (
                    "data_anonymized",
                    models.BooleanField(
                        default=False,
                        help_text="User data has been anonymized for GDPR compliance.",
                        verbose_name="data anonymized",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="WriterDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("id_proof", "ID Proof"),
                            ("degree_certificate", "Degree Certificate"),
                            ("transcript", "Academic Transcript"),
                            ("cv", "Curriculum Vitae"),
                            ("portfolio", "Writing Portfolio"),
                            ("other", "Other Document"),
                        ],
                        max_length=50,
                        verbose_name="document type",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        help_text="Upload PDF, JPG, PNG, DOC, or DOCX file. Maximum file size is 10MB.",
                        upload_to=apps.accounts.models.writer_document.writer_document_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "doc",
                                    "docx",
                                ]
                            )
                        ],
                        verbose_name="document file",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash of the uploaded file for integrity verification",
                        max_length=128,
                        verbose_name="file hash",
                    ),
                ),
                (
                    "scanned_for_virus",
                    models.BooleanField(
                        default=False, verbose_name="scanned for virus"
                    ),
                ),
                (
                    "scan_result",
                    models.TextField(
                        blank=True,
                        help_text="Result from virus scanning service",
                        verbose_name="virus scan result",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="original filename"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        help_text="Size of the uploaded file in bytes",
                        verbose_name="file size in bytes",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="MIME type"
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True,
                        help_text="Administrator notes regarding document verification",
                        verbose_name="review notes",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for document rejection if applicable",
                        verbose_name="rejection reason",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="verified at"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when this document expires and needs renewal",
                        null=True,
                        verbose_name="expires at",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reviewed by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "writer document",
                "verbose_name_plural": "writer documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WriterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Brief professional biography (max 2000 characters)",
                        max_length=2000,
                        verbose_name="biography",
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bachelors", "Bachelor's Degree"),
                            ("masters", "Master's Degree"),
                            ("phd", "PhD"),
                            ("professor", "Professor"),
                        ],
                        max_length=20,
                        verbose_name="highest education level",
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        blank=True,
                        help_text="University or institution name",
                        max_length=255,
                        verbose_name="institution",
                    ),
                ),
                (
                    "graduation_year",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="graduation year",
                    ),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(50)],
                        verbose_name="years of experience",
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Hourly rate in platform currency",
                        max_digits=8,
                        verbose_name="hourly rate",
                    ),
                ),
                (
                    "total_earnings",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total earnings from completed orders",
                        max_digits=12,
                        verbose_name="total earnings",
                    ),
                ),
                (
                    "completed_orders",
                    models.PositiveIntegerField(
                        default=0, verbose_name="completed orders"
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                        verbose_name="average rating",
                    ),
                ),
                (
                    "specialization",
                    models.TextField(
                        blank=True,
                        help_text="Areas of expertise (comma-separated)",
                        verbose_name="specialization",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, verbose_name="available for assignments"
                    ),
                ),
                (
                    "max_orders",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Maximum number of orders writer can handle simultaneously",
                        verbose_name="maximum concurrent orders",
                    ),
                ),
                (
                    "current_orders",
                    models.PositiveIntegerField(
                        default=0, verbose_name="current orders"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("under_review", "Under Review"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("disabled", "Disabled"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "profile_completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="profile completed at"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="activated at"
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(auto_now=True, verbose_name="last activity"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="writer_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "writer profile",
                "verbose_name_plural": "writer profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WriterVerificationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("registered", "Registered"),
                            ("profile_completed", "Profile Completed"),
                            ("documents_submitted", "Documents Submitted"),
                            ("under_admin_review", "Under Admin Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("revision_required", "Revision Required"),
                        ],
                        default="registered",
                        max_length=50,
                        protected=True,
                        verbose_name="verification state",
                    ),
                ),
                (
                    "profile_completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="profile completed at"
                    ),
                ),
                (
                    "documents_submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="documents submitted at"
                    ),
                ),
                (
                    "review_started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="review started at"
                    ),
                ),
                (
                    "review_completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="review completed at"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Detailed reason for rejection",
                        verbose_name="rejection reason",
                    ),
                ),
                (
                    "revision_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes on what needs to be revised",
                        verbose_name="revision notes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_verifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="approved by",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_verifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="rejected by",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_status",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "writer verification status",
                "verbose_name_plural": "writer verification statuses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="accounts_us_email_74c8d6_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["user_type"], name="accounts_us_user_ty_b6cfc8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["date_joined"], name="accounts_us_date_jo_ff39bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="writerdocument",
            index=models.Index(
                fields=["user", "document_type"], name="accounts_wr_user_id_d7cdfc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="writerdocument",
            index=models.Index(fields=["status"], name="accounts_wr_status_4ce357_idx"),
        ),
        migrations.AddIndex(
            model_name="writerdocument",
            index=models.Index(
                fields=["scanned_for_virus"], name="accounts_wr_scanned_0912c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="writerdocument",
            index=models.Index(
                fields=["expires_at"], name="accounts_wr_expires_308d55_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="writerdocument",
            unique_together={("user", "document_type", "status")},
        ),
        migrations.AddIndex(
            model_name="writerprofile",
            index=models.Index(fields=["status"], name="accounts_wr_status_4e259b_idx"),
        ),
        migrations.AddIndex(
            model_name="writerprofile",
            index=models.Index(
                fields=["education_level"], name="accounts_wr_educati_ac0cc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="writerprofile",
            index=models.Index(
                fields=["average_rating"], name="accounts_wr_average_ba652c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="writerprofile",
            index=models.Index(
                fields=["is_available"], name="accounts_wr_is_avai_0f408d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="writerverificationstatus",
            index=models.Index(fields=["state"], name="accounts_wr_state_705d1e_idx"),
        ),
        migrations.AddIndex(
            model_name="writerverificationstatus",
            index=models.Index(
                fields=["user", "state"], name="accounts_wr_user_id_4e7b9d_idx"
            ),
        ),
    ]
