# Generated by Django 5.0.14 on 2026-02-01 16:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False, help_text="Whether conversation is closed"
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        help_text="Order this conversation belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Message content", max_length=5000),
                ),
                (
                    "is_system_message",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a system-generated message",
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("admin_has_viewed", models.BooleanField(default=False)),
                ("admin_viewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="messaging.conversation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Attached file",
                        upload_to="message_attachments/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "txt",
                                    "rtf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "xls",
                                    "xlsx",
                                    "ppt",
                                    "pptx",
                                ]
                            )
                        ],
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                ("file_type", models.CharField(max_length=100)),
                (
                    "virus_scan_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("clean", "Clean"),
                            ("infected", "Infected"),
                            ("error", "Scan Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("virus_scan_result", models.TextField(blank=True, null=True)),
                ("scanned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "file_hash",
                    models.CharField(help_text="SHA-256 hash of file", max_length=64),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="messaging.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Attachment",
                "verbose_name_plural": "Message Attachments",
            },
        ),
        migrations.CreateModel(
            name="MessageReadReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("read_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_receipts",
                        to="messaging.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Read Receipt",
                "verbose_name_plural": "Read Receipts",
            },
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["order", "created_at"], name="messaging_c_order_i_2ccd22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["is_closed", "updated_at"],
                name="messaging_c_is_clos_b30d22_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="messaging_m_convers_7bc91b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "created_at"], name="messaging_m_sender__277197_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["is_read", "created_at"], name="messaging_m_is_read_0c5cc5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messageattachment",
            index=models.Index(
                fields=["message", "created_at"], name="messaging_m_message_747332_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messageattachment",
            index=models.Index(
                fields=["virus_scan_status"], name="messaging_m_virus_s_6482ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagereadreceipt",
            index=models.Index(
                fields=["message", "user"], name="messaging_m_message_b31b9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagereadreceipt",
            index=models.Index(
                fields=["user", "read_at"], name="messaging_m_user_id_55bf4d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="messagereadreceipt",
            unique_together={("message", "user")},
        ),
    ]
