# Generated by Django 4.2 on 2026-02-15 13:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import media_portfolio.projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Order for display')),
                ('title', models.CharField(help_text='The catchy name of the project', max_length=200)),
                ('slug', models.SlugField(help_text='SEO-friendly URL', max_length=250, unique=True)),
                ('short_summary', models.CharField(help_text="1-2 sentence 'elevator pitch' for quick scanning", max_length=300)),
                ('description', models.TextField(blank=True, help_text='Full project description')),
                ('problem_statement', models.TextField(blank=True, help_text="The 'Why'—what specific problem were you trying to solve?")),
                ('solution', models.TextField(blank=True, help_text="The 'How'—details on your architecture and logic")),
                ('technical_stack', models.JSONField(blank=True, default=list, help_text='List of languages and frameworks (e.g., ["Python", "React", "Django"])')),
                ('api_integrations', models.JSONField(blank=True, default=list, help_text='External services used (e.g., ["Stripe", "OpenAI", "Twilio"])')),
                ('thumbnail', models.ImageField(help_text='High-quality screenshot of the UI', upload_to=media_portfolio.projects.models.project_thumbnail_path)),
                ('thumbnail_webp', models.ImageField(blank=True, help_text='Optimized WebP version', null=True, upload_to='projects/thumbnails/webp/')),
                ('thumbnail_blur', models.ImageField(blank=True, help_text='Blurred placeholder for lazy loading', null=True, upload_to='projects/thumbnails/blur/')),
                ('github_url', models.URLField(blank=True, help_text='Link to the repository for code review')),
                ('live_demo_url', models.URLField(blank=True, help_text='Hosted version of the site')),
                ('documentation_url', models.URLField(blank=True, help_text='Link to project documentation')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', help_text='Helps recruiters see your growth from Basic to Advanced', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this project at the top of the UI')),
                ('performance_score', models.IntegerField(default=0, help_text='Lighthouse performance metric', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('stars_count', models.IntegerField(default=0, help_text='GitHub stars count (auto-updated)')),
                ('forks_count', models.IntegerField(default=0, help_text='GitHub forks count (auto-updated)')),
                ('last_github_sync', models.DateTimeField(blank=True, help_text='Last time GitHub stats were synced', null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('view_count', models.IntegerField(default=0, editable=False)),
                ('copyright_notice', models.CharField(default='© All Rights Reserved', max_length=200)),
                ('license', models.CharField(choices=[('copyright', 'All Rights Reserved'), ('mit', 'MIT License'), ('apache', 'Apache License 2.0'), ('gpl', 'GNU GPL v3'), ('bsd', 'BSD License'), ('public', 'Public Domain')], default='copyright', max_length=20)),
                ('categories', models.ManyToManyField(blank=True, help_text='Project categories', related_name='projects', to='categories.category')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-is_featured', '-performance_score', '-published_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Order for display')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Like',
                'verbose_name_plural': 'Project Likes',
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Order for display')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, help_text='Optional')),
                ('content', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('is_spam', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='projects.projectcomment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Comment',
                'verbose_name_plural': 'Project Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='projectlike',
            index=models.Index(fields=['project', 'session_key'], name='projects_pr_project_a12357_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectlike',
            unique_together={('project', 'session_key')},
        ),
        migrations.AddIndex(
            model_name='projectcomment',
            index=models.Index(fields=['project', 'is_approved'], name='projects_pr_project_837ee0_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['difficulty_level', 'is_published'], name='projects_pr_difficu_6f38b6_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-stars_count'], name='projects_pr_stars_c_0a2f82_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-published_date'], name='projects_pr_publish_5d19b2_idx'),
        ),
    ]
