# Generated by Django 4.2 on 2026-02-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Order for display')),
                ('name', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=300, unique=True)),
                ('description', models.TextField(blank=True)),
                ('html_url', models.URLField()),
                ('clone_url', models.URLField()),
                ('homepage', models.URLField(blank=True)),
                ('stars_count', models.IntegerField(default=0)),
                ('forks_count', models.IntegerField(default=0)),
                ('watchers_count', models.IntegerField(default=0)),
                ('open_issues_count', models.IntegerField(default=0)),
                ('primary_language', models.CharField(blank=True, max_length=50)),
                ('languages', models.JSONField(blank=True, default=dict)),
                ('created_at_github', models.DateTimeField()),
                ('updated_at_github', models.DateTimeField()),
                ('pushed_at_github', models.DateTimeField()),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GitHub Repository',
                'verbose_name_plural': 'GitHub Repositories',
                'ordering': ['-stars_count'],
            },
        ),
        migrations.CreateModel(
            name='GitHubSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Order for display')),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('repos_created', models.IntegerField(default=0)),
                ('repos_updated', models.IntegerField(default=0)),
                ('status', models.CharField(default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'GitHub Sync Log',
                'verbose_name_plural': 'GitHub Sync Logs',
                'ordering': ['-synced_at'],
            },
        ),
    ]
