# Generated by Django 5.0.14 on 2026-02-02 13:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CitationStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("abbreviation", models.CharField(max_length=10, unique=True)),
                (
                    "book_example",
                    models.TextField(help_text="Example citation for a book"),
                ),
                (
                    "journal_example",
                    models.TextField(
                        help_text="Example citation for a journal article"
                    ),
                ),
                (
                    "website_example",
                    models.TextField(help_text="Example citation for a website"),
                ),
                (
                    "rules",
                    models.JSONField(
                        default=dict, help_text="Formatting rules in JSON format"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Citation Style",
                "verbose_name_plural": "Citation Styles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AIToolConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tool_type",
                    models.CharField(
                        choices=[
                            ("outline_helper", "Outline Helper"),
                            ("grammar_checker", "Grammar Checker"),
                            ("citation_formatter", "Citation Formatter"),
                            ("paraphrasing_tool", "Paraphrasing Tool"),
                            ("thesis_generator", "Thesis Statement Generator"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "daily_limit_per_user",
                    models.PositiveIntegerField(
                        default=10, help_text="Maximum uses per user per day"
                    ),
                ),
                (
                    "max_input_length",
                    models.PositiveIntegerField(
                        default=5000, help_text="Maximum input characters"
                    ),
                ),
                (
                    "max_output_length",
                    models.PositiveIntegerField(
                        default=2000, help_text="Maximum output characters"
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.7,
                        help_text="Creativity/randomness (0.0-2.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(2.0),
                        ],
                    ),
                ),
                ("max_tokens", models.PositiveIntegerField(default=500)),
                ("content_filter_enabled", models.BooleanField(default=True)),
                ("plagiarism_check_enabled", models.BooleanField(default=True)),
                (
                    "require_review",
                    models.BooleanField(
                        default=False,
                        help_text="Require admin review before showing to user",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("maintenance_message", models.TextField(blank=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Tool Configuration",
                "verbose_name_plural": "AI Tool Configurations",
                "ordering": ["tool_type"],
            },
        ),
        migrations.CreateModel(
            name="AIToolTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("essay", "Essay"),
                            ("research_paper", "Research Paper"),
                            ("thesis", "Thesis/Dissertation"),
                            ("literature_review", "Literature Review"),
                            ("case_study", "Case Study"),
                            ("lab_report", "Lab Report"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "sections",
                    models.JSONField(
                        default=list,
                        help_text="List of section names for this template type",
                    ),
                ),
                (
                    "guidelines",
                    models.TextField(help_text="General guidelines for this type"),
                ),
                (
                    "common_mistakes",
                    models.TextField(blank=True, help_text="Common mistakes to avoid"),
                ),
                (
                    "recommended_sources",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Recommended sources or databases",
                    ),
                ),
                ("example_outline", models.TextField(blank=True)),
                ("example_thesis", models.TextField(blank=True)),
                (
                    "academic_level",
                    models.CharField(
                        choices=[
                            ("high_school", "High School"),
                            ("undergraduate", "Undergraduate"),
                            ("graduate", "Graduate"),
                            ("phd", "PhD"),
                        ],
                        default="undergraduate",
                        max_length=50,
                    ),
                ),
                (
                    "word_count_range",
                    models.CharField(
                        blank=True, help_text="e.g., 1500-2000 words", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Tool Template",
                "verbose_name_plural": "AI Tool Templates",
                "ordering": ["template_type", "academic_level"],
                "unique_together": {("template_type", "academic_level")},
            },
        ),
        migrations.CreateModel(
            name="CitationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("citation_style", models.CharField(max_length=50)),
                ("source_data", models.JSONField()),
                ("formatted_citation", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GrammarCheckRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("input_text", models.TextField()),
                ("language", models.CharField(default="en", max_length=10)),
                ("suggestions", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grammar_check_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OutlineRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
                ("outline_type", models.CharField(max_length=50)),
                ("generated_outline", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outline_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAILimits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("outline_helper_used_today", models.PositiveIntegerField(default=0)),
                ("grammar_checker_used_today", models.PositiveIntegerField(default=0)),
                (
                    "citation_formatter_used_today",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "paraphrasing_tool_used_today",
                    models.PositiveIntegerField(default=0),
                ),
                ("thesis_generator_used_today", models.PositiveIntegerField(default=0)),
                ("last_reset_date", models.DateField(auto_now_add=True)),
                ("total_uses", models.PositiveIntegerField(default=0)),
                (
                    "is_restricted",
                    models.BooleanField(
                        default=False,
                        help_text="User is restricted from using AI tools",
                    ),
                ),
                ("restriction_reason", models.TextField(blank=True)),
                ("restricted_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_limits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User AI Limits",
                "verbose_name_plural": "User AI Limits",
            },
        ),
        migrations.CreateModel(
            name="AIToolUsageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tool_type",
                    models.CharField(
                        choices=[
                            ("outline_helper", "Outline Helper"),
                            ("grammar_checker", "Grammar Checker"),
                            ("citation_formatter", "Citation Formatter"),
                            ("paraphrasing_tool", "Paraphrasing Tool"),
                            ("thesis_generator", "Thesis Statement Generator"),
                        ],
                        max_length=50,
                    ),
                ),
                ("input_text", models.TextField()),
                ("output_text", models.TextField()),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("has_disclaimer", models.BooleanField(default=True)),
                ("is_reviewed", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_ai_outputs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_tool_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Tool Usage Log",
                "verbose_name_plural": "AI Tool Usage Logs",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_review_ai_output", "Can review AI tool outputs"),
                    ("can_export_ai_logs", "Can export AI tool usage logs"),
                ],
                "indexes": [
                    models.Index(
                        fields=["user", "tool_type"],
                        name="ai_tools_ai_user_id_845564_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="ai_tools_ai_created_641530_idx"
                    ),
                    models.Index(
                        fields=["session_id"], name="ai_tools_ai_session_0a1acb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WritingFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("grammar", "Grammar"),
                            ("style", "Writing Style"),
                            ("structure", "Structure"),
                            ("clarity", "Clarity"),
                            ("coherence", "Coherence"),
                            ("argument", "Argument Strength"),
                        ],
                        max_length=50,
                    ),
                ),
                ("original_text", models.TextField()),
                ("issues_found", models.JSONField(blank=True, default=list)),
                ("suggestions", models.TextField()),
                ("corrected_text", models.TextField(blank=True)),
                (
                    "score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0.8,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("word_count", models.PositiveIntegerField()),
                (
                    "reading_time",
                    models.PositiveIntegerField(
                        help_text="Estimated reading time in minutes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="writing_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Writing Feedback",
                "verbose_name_plural": "Writing Feedback",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "feedback_type"],
                        name="ai_tools_wr_user_id_80834f_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="ai_tools_wr_created_3b3922_idx"
                    ),
                ],
            },
        ),
    ]
