# Generated by Django 4.2 on 2026-02-15 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Order for display')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('category_type', models.CharField(choices=[('medium', 'Medium (Photography/Video/3D/Design)'), ('genre', 'Genre (Portrait/Landscape/Abstract/Street)'), ('technique', 'Technique (Digital/Film/Analog/Timelapse)'), ('subject', 'Subject (People/Nature/Architecture/Products)'), ('collection', 'Collection/Series'), ('client', 'Client Work'), ('personal', 'Personal Projects')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Cover image for this category', null=True, upload_to='categories/covers/')),
                ('icon', models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fa-camera')", max_length=50)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='categories.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['category_type', 'sort_order', 'name'],
            },
        ),
    ]
