# Generated by Django 4.2 on 2026-02-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Order for display')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=350, unique=True)),
                ('source', models.CharField(choices=[('devto', 'Dev.to'), ('medium', 'Medium'), ('custom', 'Custom')], default='devto', max_length=20)),
                ('external_id', models.CharField(blank=True, help_text='External post ID', max_length=100)),
                ('external_url', models.URLField()),
                ('excerpt', models.TextField(help_text='Short excerpt/summary')),
                ('content', models.TextField(blank=True, help_text='Full content (if available)')),
                ('cover_image', models.URLField(blank=True, help_text='Cover image URL')),
                ('author_name', models.CharField(default='Author', max_length=100)),
                ('published_at', models.DateTimeField()),
                ('read_time_minutes', models.IntegerField(default=0)),
                ('reactions_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Order for display')),
                ('source', models.CharField(choices=[('devto', 'Dev.to'), ('medium', 'Medium'), ('custom', 'Custom')], max_length=20)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('posts_created', models.IntegerField(default=0)),
                ('posts_updated', models.IntegerField(default=0)),
                ('status', models.CharField(default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Blog Sync Log',
                'verbose_name_plural': 'Blog Sync Logs',
                'ordering': ['-synced_at'],
            },
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['source', '-published_at'], name='blog_blogpo_source_54a8e8_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_featured', '-published_at'], name='blog_blogpo_is_feat_1c3903_idx'),
        ),
    ]
