# Generated by Django 5.0.14 on 2026-02-02 11:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataRetentionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="rule name"
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("user_account", "User Account"),
                            ("order_data", "Order Data"),
                            ("payment_data", "Payment Data"),
                            ("communication", "Communication"),
                            ("logs", "System Logs"),
                            ("backups", "Backup Data"),
                        ],
                        max_length=50,
                        verbose_name="data type",
                    ),
                ),
                (
                    "retention_period_days",
                    models.PositiveIntegerField(
                        help_text="Number of days to retain data before taking action",
                        verbose_name="retention period (days)",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("anonymize", "Anonymize"),
                            ("delete", "Delete"),
                            ("archive", "Archive"),
                        ],
                        max_length=50,
                        verbose_name="action type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the rule",
                        verbose_name="description",
                    ),
                ),
                (
                    "legal_basis",
                    models.TextField(
                        blank=True,
                        help_text="Legal basis for retention period (GDPR Article)",
                        verbose_name="legal basis",
                    ),
                ),
                (
                    "last_executed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last executed"
                    ),
                ),
                (
                    "items_processed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="items processed"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "data retention rule",
                "verbose_name_plural": "data retention rules",
                "ordering": ["data_type", "retention_period_days"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="log ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("view", "View"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("export", "Export"),
                            ("import", "Import"),
                        ],
                        max_length=50,
                        verbose_name="action type",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Name of the Django model",
                        max_length=100,
                        verbose_name="model name",
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the affected object",
                        max_length=100,
                        verbose_name="object ID",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        help_text="Detailed changes made (JSON format)",
                        null=True,
                        verbose_name="changes",
                    ),
                ),
                (
                    "before_state",
                    models.JSONField(
                        blank=True,
                        help_text="Object state before action",
                        null=True,
                        verbose_name="before state",
                    ),
                ),
                (
                    "after_state",
                    models.JSONField(
                        blank=True,
                        help_text="Object state after action",
                        null=True,
                        verbose_name="after state",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
                (
                    "request_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="request path"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="session key"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="timestamp"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "audit log",
                "verbose_name_plural": "audit logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["log_id"], name="compliance__log_id_9d4ab3_idx"
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="compliance__user_id_761f53_idx",
                    ),
                    models.Index(
                        fields=["model_name", "object_id"],
                        name="compliance__model_n_d2788f_idx",
                    ),
                    models.Index(
                        fields=["action_type", "timestamp"],
                        name="compliance__action__c44bf8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConsentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="log ID",
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("registration", "Registration"),
                            ("terms", "Terms of Service"),
                            ("privacy", "Privacy Policy"),
                            ("marketing", "Marketing Emails"),
                            ("cookies", "Cookies"),
                            ("data_processing", "Data Processing"),
                        ],
                        max_length=50,
                        verbose_name="consent type",
                    ),
                ),
                (
                    "consent_given",
                    models.BooleanField(
                        default=True,
                        help_text="Whether consent was given (True) or withdrawn (False)",
                        verbose_name="consent given",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
                (
                    "consent_text",
                    models.TextField(
                        blank=True,
                        help_text="Exact text of what was consented to",
                        verbose_name="consent text",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="Version of terms/privacy policy at time of consent",
                        max_length=20,
                        verbose_name="version",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "consent log",
                "verbose_name_plural": "consent logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "consent_type"],
                        name="compliance__user_id_0c33f5_idx",
                    ),
                    models.Index(
                        fields=["consent_type"], name="compliance__consent_434dcf_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="compliance__created_e02183_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DataRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="request ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("access", "Data Access Request"),
                            ("rectification", "Data Rectification"),
                            ("erasure", "Right to be Forgotten"),
                            ("restriction", "Processing Restriction"),
                            ("portability", "Data Portability"),
                            ("objection", "Objection to Processing"),
                        ],
                        max_length=50,
                        verbose_name="request type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("verifying", "Verifying Identity"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("appealed", "Appealed"),
                        ],
                        default="received",
                        max_length=50,
                        verbose_name="status",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the request",
                        verbose_name="description",
                    ),
                ),
                (
                    "verification_method",
                    models.CharField(
                        blank=True,
                        help_text="Method used to verify user identity",
                        max_length=100,
                        verbose_name="verification method",
                    ),
                ),
                (
                    "verification_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="verification date"
                    ),
                ),
                (
                    "processing_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about request processing",
                        verbose_name="processing notes",
                    ),
                ),
                (
                    "data_provided",
                    models.TextField(
                        blank=True,
                        help_text="Summary of data provided to user",
                        verbose_name="data provided",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to exported data file",
                        max_length=500,
                        verbose_name="file path",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for request rejection if applicable",
                        verbose_name="rejection reason",
                    ),
                ),
                (
                    "appeal_notes",
                    models.TextField(blank=True, verbose_name="appeal notes"),
                ),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="received at"),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        help_text="Legal deadline for request completion (30 days from receipt)",
                        verbose_name="due date",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="verified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "data request",
                "verbose_name_plural": "data requests",
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["request_id"], name="compliance__request_7e82a0_idx"
                    ),
                    models.Index(
                        fields=["user", "status"], name="compliance__user_id_ef10cc_idx"
                    ),
                    models.Index(
                        fields=["status", "due_date"],
                        name="compliance__status_d675ae_idx",
                    ),
                    models.Index(
                        fields=["request_type"], name="compliance__request_f4b537_idx"
                    ),
                ],
            },
        ),
    ]
