# Generated by Django 5.0.14 on 2026-02-01 16:41

import django.db.models.deletion
import django_fsm
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "__first__"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RevisionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "instructions",
                    models.TextField(
                        help_text="Detailed revision instructions from client"
                    ),
                ),
                ("deadline", models.DateTimeField()),
                ("max_revisions_allowed", models.PositiveSmallIntegerField(default=3)),
                ("revisions_used", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("requested", "Requested"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="requested",
                        max_length=50,
                        protected=True,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revision_requests",
                        to="orders.order",
                    ),
                ),
                (
                    "original_files",
                    models.ManyToManyField(
                        blank=True,
                        related_name="revision_originals",
                        to="documents.document",
                    ),
                ),
                (
                    "revised_files",
                    models.ManyToManyField(
                        blank=True,
                        related_name="revision_outputs",
                        to="documents.document",
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="writer_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Revision Request",
                "verbose_name_plural": "Revision Requests",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="RevisionCycle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("max_revisions_allowed", models.PositiveSmallIntegerField(default=3)),
                ("revisions_used", models.PositiveSmallIntegerField(default=0)),
                ("revision_period_days", models.PositiveSmallIntegerField(default=14)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ends_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revision_cycle",
                        to="orders.order",
                    ),
                ),
                (
                    "revision_requests",
                    models.ManyToManyField(
                        blank=True,
                        related_name="cycles",
                        to="revisions.revisionrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Revision Cycle",
                "verbose_name_plural": "Revision Cycles",
            },
        ),
        migrations.CreateModel(
            name="RevisionAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("requested", "Revision Requested"),
                            ("started", "Revision Started"),
                            ("file_uploaded", "File Uploaded"),
                            ("file_downloaded", "File Downloaded"),
                            ("completed", "Revision Completed"),
                            ("cancelled", "Revision Cancelled"),
                            ("deadline_extended", "Deadline Extended"),
                            ("status_changed", "Status Changed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        default=dict, help_text="JSON details of the action"
                    ),
                ),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revision_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="revisions.revisionrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Revision Audit Log",
                "verbose_name_plural": "Revision Audit Logs",
                "ordering": ["-performed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="revisionrequest",
            index=models.Index(
                fields=["order", "status"], name="revisions_r_order_i_f6df4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="revisionrequest",
            index=models.Index(
                fields=["deadline"], name="revisions_r_deadlin_00bdcd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="revisionrequest",
            index=models.Index(
                fields=["client", "status"], name="revisions_r_client__2f7af5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="revisioncycle",
            index=models.Index(
                fields=["order", "is_active"], name="revisions_r_order_i_119d4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="revisioncycle",
            index=models.Index(
                fields=["ends_at"], name="revisions_r_ends_at_1f9110_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="revisionauditlog",
            index=models.Index(
                fields=["revision", "performed_at"],
                name="revisions_r_revisio_e4e43e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="revisionauditlog",
            index=models.Index(
                fields=["action", "performed_at"], name="revisions_r_action_1fc8ee_idx"
            ),
        ),
    ]
