# Generated by Django 4.2.7 on 2026-02-13 23:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Order for display')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('collection_type', models.CharField(choices=[('series', 'Series'), ('exhibition', 'Exhibition'), ('project', 'Project'), ('client', 'Client Work'), ('personal', 'Personal'), ('award', 'Award Winning')], default='series', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Cover image for the collection', null=True, upload_to='collections/covers/')),
                ('layout', models.CharField(choices=[('grid', 'Grid'), ('masonry', 'Masonry'), ('slideshow', 'Slideshow'), ('carousel', 'Carousel')], default='grid', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'ordering': ['-featured', '-published_date'],
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('custom_caption', models.TextField(blank=True, help_text="Override the media item's caption for this collection")),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collections.collection')),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.mediaitem')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('collection', 'media_item')},
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='media_items',
            field=models.ManyToManyField(blank=True, related_name='collections', through='collections.CollectionItem', to='media.mediaitem'),
        ),
    ]
