# Generated by Django 4.2.7 on 2026-02-13 23:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Order for display')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('website', models.URLField(blank=True, help_text='Optional: Your website or portfolio')),
                ('content', models.TextField()),
                ('is_approved', models.BooleanField(default=False, help_text='Approve for public display')),
                ('is_spam', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this comment as a testimonial')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('can_use_as_testimonial', models.BooleanField(default=False, help_text='Can I feature this comment on my site?')),
                ('testimonial_approved', models.BooleanField(default=False, help_text='Approved to use as testimonial')),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='media.mediaitem')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Order for display')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, help_text='e.g., Client, Art Director', max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, help_text='Rating out of 5')),
                ('featured', models.BooleanField(default=True)),
                ('source_comment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonial', to='comments.comment')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['media_item', 'is_approved'], name='comments_co_media_i_a3afee_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['is_featured'], name='comments_co_is_feat_85e01a_idx'),
        ),
    ]
